######################################
#log
######################################
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    liquibase.statement: trace
  path: ~/log/versionable-helper/
  file: versionable-helper.log


######################################
#datasource
######################################
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Data/H2/VersionableDemo
    username: sa
    password: 123456

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml