######################################
 #datasource
######################################
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Data/H2/VersionableDemo
    username: sa
    password: 123456

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true